### ISSUE TITLE
Pre-trained OpenCabinetDrawer RL models

### ISSUE THREAD

**Issue by arjung128** [haosulab/ManiSkill-Learn#18]
When I evaluate the example pre-trained model using the provided script:

```
python -m tools.run_rl configs/bc/mani_skill_point_cloud_transformer.py \
--gpu-ids=0 --cfg-options "env_cfg.env_name=OpenCabinetDrawer_1045_link_0-v0" \
"eval_cfg.save_video=True" "eval_cfg.num=10" "eval_cfg.use_log=True" \
--work-dir=./test/OpenCabinetDrawer_1045_link_0-v0_pcd \
--resume-from=./example_mani_skill_data/OpenCabinetDrawer_1045_link_0-v0_PN_Transformer.ckpt --evaluation
```

During training:
- Is this model trained on a single object instance, or multiple object instances within a category?
- As for the variation in the environment, is the only variation (a) robot position, and (b) environment parameters e.g. robot friction during training?

At test time:
- Is this being tested on an unseen object instance from the same category as training?

Thanks!

**Comment by xuanlinli17** [comment]
```
Is this model trained on a single object instance, or multiple object instances within a category?

Is this being tested on an unseen object instance from the same category as training?
```

The script has `--evaluation` so it's evaluating an existing model (and not training a new model) on an environment. The environment being evaluated on is `env_cfg.env_name=OpenCabinetDrawer_1045_link_0-v0` and since the name is `OpenCabinetDrawer_1045_link_0-v0`, it is evaluating on a single object instance (if it were evaluating on multiple object instances, then the config should have been `env_cfg.env_name=OpenCabinetDrawer-v0`). The model being loaded is `OpenCabinetDrawer_1045_link_0-v0_PN_Transformer.ckpt`, so the model being loaded was trained on a single environment `OpenCabinetDrawer_1045_link_0-v0`, i.e. `link_0` of object `OpenCabinetDrawer_1045`. Evaluation was done on the same link and object the model was trained.

```
As for the variation in the environment, is the only variation (a) robot position, and (b) environment parameters e.g. robot friction during training?
```
Yes

**Comment by xuanlinli17** [comment]
Scripts for evaluating pretrained models on all training objects are in `scripts/full_mani_skill_example`

**Comment by arjung128** [comment]
Got it, thanks!
